spring.application.name=TripToday
server.port=3000

#auth0.domain: dev-an6hxzzvf6uoryjw.us.auth0.com
#auth0.clientId: F5gDUwTRwbqS1lJPLr0Dts4oRBrr1G8D
#auth0.clientSecret: JTu72ekX_hQeU4ZVbsI5CRCTVnUaBACdR6h0Zn1J-6itYA2RFkUhHqyUlnzHbLeS
#
#spring.security.oauth2.client.registration.auth0.provider=okta
#spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.auth0.scope=openid
#spring.security.oauth2.client.registration.auth0.client-id=F5gDUwTRwbqS1lJPLr0Dts4oRBrr1G8D
#spring.security.oauth2.client.registration.auth0.client-secret=JTu72ekX_hQeU4ZVbsI5CRCTVnUaBACdR6h0Zn1J-6itYA2RFkUhHqyUlnzHbLeS
#spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.auth0.client-authentication-method=client_secret_basic
#spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-an6hxzzvf6uoryjw.us.auth0.com/
#auth0.audience=https://dev-an6hxzzvf6uoryjw.us.auth0.com/api/v2/

okta.oauth2.issuer=https://dev-an6hxzzvf6uoryjw.us.auth0.com/
okta.oauth2.client-id=F5gDUwTRwbqS1lJPLr0Dts4oRBrr1G8D
okta.oauth2.client-secret=JTu72ekX_hQeU4ZVbsI5CRCTVnUaBACdR6h0Zn1J-6itYA2RFkUhHqyUlnzHbLeS