spring.application.name=TripToday
server.port=3000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
okta.oauth2.issuer=https://dev-an6hxzzvf6uoryjw.us.auth0.com/
okta.oauth2.client-id=F5gDUwTRwbqS1lJPLr0Dts4oRBrr1G8D
okta.oauth2.client-secret=JTu72ekX_hQeU4ZVbsI5CRCTVnUaBACdR6h0Zn1J-6itYA2RFkUhHqyUlnzHbLeS

